language: php

sudo: false

branches:
  only:
    - master
    - develop

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - nightly

notifications:
  email: false